/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout (invalida o refresh token).
         * @description Invalida (blacklist) o refresh token do usuário autenticado.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Esqueci minha senha.
         * @description Solicita a redefinição de senha por e-mail (esqueci minha senha).
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirma redefinição de senha.
         * @description Confirma a nova senha a partir do uid + token recebidos por e-mail.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria um novo usuário (cadastro).
         * @description Cria um novo usuário (cadastro).
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resumo do dashboard.
         * @description Contagens agregadas para o dashboard: pendentes, vencidas, hoje e concluídas na semana.
         */
        get: operations["dashboard_summary_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/upcoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Próximas tarefas do dashboard.
         * @description Tarefas vencidas, próximas do prazo (7 dias) e de alta prioridade para o dashboard.
         */
        get: operations["dashboard_upcoming_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as listas de tarefas.
         * @description Lista as listas de tarefas (TaskList) pertencentes ao usuário autenticado.
         */
        get: operations["lists_list"];
        put?: never;
        /**
         * Cria uma lista de tarefas.
         * @description Cria uma nova lista de tarefas (TaskList) para o usuário autenticado.
         */
        post: operations["lists_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lists/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma lista de tarefas.
         * @description Retorna os dados de uma lista de tarefas do usuário autenticado.
         */
        get: operations["lists_retrieve"];
        /**
         * Atualiza uma lista de tarefas.
         * @description Atualiza integralmente uma lista de tarefas do usuário autenticado.
         */
        put: operations["lists_update"];
        post?: never;
        /**
         * Remove uma lista de tarefas.
         * @description Remove uma lista de tarefas do usuário autenticado.
         */
        delete: operations["lists_destroy"];
        options?: never;
        head?: never;
        /**
         * Atualiza parcialmente uma lista de tarefas.
         * @description Atualiza parcialmente uma lista de tarefas do usuário autenticado.
         */
        patch: operations["lists_partial_update"];
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subtasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as subtarefas.
         * @description Lista as subtarefas vinculadas às tarefas do usuário autenticado.
         */
        get: operations["subtasks_list"];
        put?: never;
        /**
         * Cria uma subtarefa.
         * @description Cria uma nova subtarefa vinculada a uma tarefa do usuário autenticado.
         */
        post: operations["subtasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subtasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma subtarefa.
         * @description Retorna os dados de uma subtarefa do usuário autenticado.
         */
        get: operations["subtasks_retrieve"];
        /**
         * Atualiza uma subtarefa.
         * @description Atualiza integralmente uma subtarefa do usuário autenticado.
         */
        put: operations["subtasks_update"];
        post?: never;
        /**
         * Remove uma subtarefa.
         * @description Remove uma subtarefa do usuário autenticado.
         */
        delete: operations["subtasks_destroy"];
        options?: never;
        head?: never;
        /**
         * Atualiza parcialmente uma subtarefa.
         * @description Atualiza parcialmente uma subtarefa do usuário autenticado.
         */
        patch: operations["subtasks_partial_update"];
        trace?: never;
    };
    "/api/subtasks/{id}/toggle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alterna status da subtarefa.
         * @description Alterna a subtarefa entre feita e pendente.
         */
        post: operations["subtasks_toggle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista as tarefas.
         * @description Lista as tarefas do usuário autenticado, ordenadas por status, prazo e título.
         */
        get: operations["tasks_list"];
        put?: never;
        /**
         * Cria uma tarefa.
         * @description Cria uma nova tarefa vinculada a uma lista do usuário autenticado.
         */
        post: operations["tasks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalha uma tarefa.
         * @description Retorna os dados de uma tarefa do usuário autenticado.
         */
        get: operations["tasks_retrieve"];
        /**
         * Atualiza uma tarefa.
         * @description Atualiza integralmente uma tarefa do usuário autenticado.
         */
        put: operations["tasks_update"];
        post?: never;
        /**
         * Remove uma tarefa.
         * @description Remove uma tarefa do usuário autenticado.
         */
        delete: operations["tasks_destroy"];
        options?: never;
        head?: never;
        /**
         * Atualiza parcialmente uma tarefa.
         * @description Atualiza parcialmente uma tarefa do usuário autenticado.
         */
        patch: operations["tasks_partial_update"];
        trace?: never;
    };
    "/api/tasks/{id}/toggle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Alterna status da tarefa.
         * @description Alterna o status da tarefa entre concluída e pendente.
         */
        post: operations["tasks_toggle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/completed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tarefas concluídas.
         * @description Lista as tarefas concluídas do usuário autenticado.
         */
        get: operations["tasks_completed_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/late/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tarefas atrasadas.
         * @description Lista as tarefas pendentes com prazo (due_date) já vencido.
         */
        get: operations["tasks_late_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/today/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tarefas de hoje.
         * @description Lista as tarefas planejadas ou com prazo (due_date) para hoje.
         */
        get: operations["tasks_today_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dados do usuário autenticado.
         * @description Retorna os dados do usuário autenticado (página do usuário).
         */
        get: operations["users_me_retrieve"];
        /** @description Retorna ou atualiza os dados do usuário autenticado (página do usuário). */
        put: operations["users_me_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza dados do usuário autenticado.
         * @description Atualiza parcialmente os dados da conta do usuário autenticado (ex.: e-mail).
         */
        patch: operations["users_me_partial_update"];
        trace?: never;
    };
    "/api/users/me/change-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Troca de senha.
         * @description Troca a senha do usuário autenticado, exigindo a senha atual.
         */
        post: operations["users_me_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Troca de senha do usuário autenticado, exigindo a senha atual. */
        ChangePassword: {
            current_password: string;
            new_password: string;
        };
        /** @description Contagens agregadas exibidas no painel inicial do dashboard. */
        DashboardSummary: {
            pending: number;
            overdue: number;
            today: number;
            completed_week: number;
        };
        /** @description Invalida o refresh token do usuário, colocando-o na blacklist. */
        Logout: {
            refresh: string;
        };
        /** @description Confirma a nova senha a partir do uid + token recebidos por e-mail. */
        PasswordResetConfirm: {
            uid: string;
            token: string;
            new_password: string;
        };
        /** @description Solicita o envio do e-mail de redefinição de senha (esqueci minha senha). */
        PasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Serializer de subtarefas (SubTask), vinculadas a uma Task do usuário autenticado. */
        PatchedSubTask: {
            readonly id?: number;
            task?: number;
            title?: string;
            done?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        /** @description Serializer de tarefas (Task), vinculadas a uma TaskList do usuário autenticado. */
        PatchedTask: {
            readonly id?: number;
            task_list?: number;
            readonly owner?: number | null;
            title?: string;
            description?: string;
            priority?: components["schemas"]["PriorityEnum"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: date */
            due_date?: string | null;
            /** Format: date */
            planned_date?: string | null;
            readonly done?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer de listas de tarefas (TaskList) do usuário autenticado. */
        PatchedTaskList: {
            readonly id?: number;
            name?: string;
            description?: string | null;
            color?: string;
            readonly user?: number;
            /** Format: date-time */
            readonly created_at?: string;
            readonly pending_count?: number;
        };
        /** @description Dados da conta do usuário autenticado (página do usuário). */
        PatchedUser: {
            readonly id?: number;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            readonly username?: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            /**
             * Data de registro
             * Format: date-time
             */
            readonly date_joined?: string;
        };
        /**
         * @description * `low` - Baixa
         *     * `medium` - Média
         *     * `high` - Alta
         * @enum {string}
         */
        PriorityEnum: "low" | "medium" | "high";
        /** @description Cria um novo usuário, validando e gravando a senha com hash (create_user). */
        Register: {
            readonly id: number;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            username: string;
            /** Format: email */
            email: string;
            password: string;
        };
        /**
         * @description * `pending` - Pendente
         *     * `in_progress` - Em andamento
         *     * `done` - Concluída
         * @enum {string}
         */
        StatusEnum: "pending" | "in_progress" | "done";
        /** @description Serializer de subtarefas (SubTask), vinculadas a uma Task do usuário autenticado. */
        SubTask: {
            readonly id: number;
            task: number;
            title: string;
            done?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Serializer de tarefas (Task), vinculadas a uma TaskList do usuário autenticado. */
        Task: {
            readonly id: number;
            task_list: number;
            readonly owner: number | null;
            title: string;
            description?: string;
            priority?: components["schemas"]["PriorityEnum"];
            status?: components["schemas"]["StatusEnum"];
            /** Format: date */
            due_date?: string | null;
            /** Format: date */
            planned_date?: string | null;
            readonly done: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer de listas de tarefas (TaskList) do usuário autenticado. */
        TaskList: {
            readonly id: number;
            name: string;
            description?: string | null;
            color?: string;
            readonly user: number;
            /** Format: date-time */
            readonly created_at: string;
            readonly pending_count: number;
        };
        TokenObtainPair: {
            username: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /** @description Dados da conta do usuário autenticado (página do usuário). */
        User: {
            readonly id: number;
            /**
             * Usuário
             * @description Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.
             */
            readonly username: string;
            /**
             * Endereço de email
             * Format: email
             */
            email?: string;
            /** Primeiro nome */
            first_name?: string;
            /** Último nome */
            last_name?: string;
            /**
             * Data de registro
             * Format: date-time
             */
            readonly date_joined: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Logout"];
                "application/x-www-form-urlencoded": components["schemas"]["Logout"];
                "multipart/form-data": components["schemas"]["Logout"];
            };
        };
        responses: {
            /** @description Token invalidado com sucesso. */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Mensagem genérica de confirmação (não revela se o e-mail existe). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Senha redefinida com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Register"];
                };
            };
        };
    };
    dashboard_summary_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    dashboard_upcoming_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    lists_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"][];
                };
            };
        };
    };
    lists_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskList"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskList"];
                "multipart/form-data": components["schemas"]["TaskList"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
        };
    };
    lists_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task list. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
        };
    };
    lists_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task list. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskList"];
                "application/x-www-form-urlencoded": components["schemas"]["TaskList"];
                "multipart/form-data": components["schemas"]["TaskList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
        };
    };
    lists_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task list. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    lists_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task list. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTaskList"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTaskList"];
                "multipart/form-data": components["schemas"]["PatchedTaskList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskList"];
                };
            };
        };
    };
    schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "ht" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    subtasks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"][];
                };
            };
        };
    };
    subtasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubTask"];
                "application/x-www-form-urlencoded": components["schemas"]["SubTask"];
                "multipart/form-data": components["schemas"]["SubTask"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"];
                };
            };
        };
    };
    subtasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este sub task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"];
                };
            };
        };
    };
    subtasks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este sub task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubTask"];
                "application/x-www-form-urlencoded": components["schemas"]["SubTask"];
                "multipart/form-data": components["schemas"]["SubTask"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"];
                };
            };
        };
    };
    subtasks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este sub task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subtasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este sub task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSubTask"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSubTask"];
                "multipart/form-data": components["schemas"]["PatchedSubTask"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"];
                };
            };
        };
    };
    subtasks_toggle_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este sub task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubTask"];
                };
            };
        };
    };
    tasks_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    tasks_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
                "application/x-www-form-urlencoded": components["schemas"]["Task"];
                "multipart/form-data": components["schemas"]["Task"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Task"];
                "application/x-www-form-urlencoded": components["schemas"]["Task"];
                "multipart/form-data": components["schemas"]["Task"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tasks_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedTask"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedTask"];
                "multipart/form-data": components["schemas"]["PatchedTask"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_toggle_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Um valor inteiro único que identifica este task. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
        };
    };
    tasks_completed_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    tasks_late_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    tasks_today_list: {
        parameters: {
            query?: {
                /** @description Qual campo usar ao ordenar os resultados. */
                ordering?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["User"];
                "application/x-www-form-urlencoded": components["schemas"]["User"];
                "multipart/form-data": components["schemas"]["User"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUser"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
                "multipart/form-data": components["schemas"]["PatchedUser"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_me_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePassword"];
                "multipart/form-data": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Senha atualizada com sucesso. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
